apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-testapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp2
  template:
    metadata:
      labels:
        app: testapp2
    spec:
      restartPolicy: Always
      containers:
        - name: test-app2
          image: mcr.microsoft.com/dotnet/samples:aspnetapp
          imagePullPolicy: Always
          env:
          - name: DOTNET_DiagnosticPorts
            value: /diag/dotnet-monitor.sock
          - name: ASPNETCORE_URLS
            value: http://+:82
          ports:
            - containerPort: 82
          volumeMounts:
            - mountPath: /diag
              name: diagvol
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
      volumes:
        - name: diagvol
          persistentVolumeClaim:
            claimName: diag-pvc

